name: nitymulya
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  fl_chart: ^1.0.0
  shared_preferences: ^2.0.17
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  email_auth: ^2.0.0
  fluttertoast: ^8.2.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/font.jpeg
    - assets/image/logo.jpeg
    - assets/lang/en.json
    - assets/lang/bn.json
    - assets/image/1.jpg
    - assets/image/2.jpg
    - assets/image/3.jpg
    - assets/image/4.jpg  
    - assets/image/5.jpg
    - assets/image/6.jpg    
    - assets/image/7.jpg
    - assets/image/8.jpg
    - assets/image/9.jpg
    - assets/image/10.jpg
    - assets/image/11.jpg
    - assets/image/12.jpg
    - assets/image/13.jpg   
    - assets/image/14.jpg
