name: nitymulya
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  fl_chart: ^1.0.0
  shared_preferences: ^2.0.17
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  email_auth: ^2.0.0
  fluttertoast: ^8.2.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^8.0.0
  geolocator: ^10.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env.local
    - assets/image/font.jpeg
    - assets/image/logo.jpeg
    - assets/lang/en.json
    - assets/lang/bn.json
    - assets/image/1.jpg
    - assets/image/2.jpg
    - assets/image/3.jpg
    - assets/image/4.jpg
    - assets/image/5.jpg
    - assets/image/6.jpg
    - assets/image/7.jpg
    - assets/image/8.jpg
    - assets/image/9.jpg
    - assets/image/10.jpg
    - assets/image/11.jpg
    - assets/image/12.jpg
    - assets/image/13.jpg
    - assets/image/14.jpg
    - assets/image/miniketchal.jpeg
    - assets/image/ataschal.jpeg
    - assets/image/Motachal.jpeg
    - assets/image/sadaata.jpeg
    - assets/image/atapacket.jpeg
    - assets/image/Moydakhola.jpeg
    - assets/image/MOYDAPACKET.jpeg
    - assets/image/TElkhola.jpeg
    - assets/image/tel1liter.jpeg
    - assets/image/tel2liter.jpeg
    - assets/image/tel5liter.jpeg
    - assets/image/pumoil.jpeg
    - assets/image/superpumoil.jpeg
    - assets/image/ricebunoil.jpeg
    - assets/image/dalmota.jpeg
    - assets/image/dalmajhari.jpeg
    - assets/image/dalchoto.jpeg
    - assets/image/mugdal.jpeg
    - assets/image/ankordal.jpeg
    - assets/image/chola.jpeg
    - assets/image/alu.jpeg
    - assets/image/deshipeyaj.jpeg
    - assets/image/bideshipeyej.jpeg
    - assets/image/rushundeshi.jpeg
    - assets/image/Rushunbideshi.jpeg
    - assets/image/morichdeshi.jpeg
    - assets/image/morichbideshi.jpeg
    - assets/image/deshiholud.jpeg
    - assets/image/bideshiholud.jpeg
    - assets/image/deshiada.jpeg
    - assets/image/bideshiada.jpeg
    - assets/image/jera.jpeg
    - assets/image/daruchini.jpeg
    - assets/image/lobonggo.jpeg
    - assets/image/alach.jpeg
    - assets/image/dhonepata.jpeg
    - assets/image/tejpata.jpeg
    - assets/image/ruimach.jpeg
    - assets/image/elishmach.jpeg
    - assets/image/gorurmansho.jpeg
    - assets/image/chagolmeat.jpeg
    - assets/image/boilarmansho.jpeg
    - assets/image/deshimurgi.jpeg
    - assets/image/dano.jpeg
    - assets/image/diplomadudh.jpeg
    - assets/image/freshdudh.jpeg
    - assets/image/marks.jpeg
    - assets/image/suger.jpeg
    - assets/image/khejur.jpeg
    - assets/image/salt.jpeg
    - assets/image/egg.jpeg
    - assets/image/khagoj.jpeg
