
import json
import os

file_path = 'banglish_dictionary.json'

# Large dataset to append
new_data = {
    # Pronouns & People
    "uni": "উনি", "unar": "উনার", "unake": "উনাকে",
    "ini": "ইনি", "inar": "ইনার", "inake": "ইনাকে",
    "or": "ওর", "oke": "ওকে", "oder": "ওদের",
    "baba": "বাবা", "abbu": "আব্বু", "pit": "পিতা", "father": "বাবা",
    "ma": "মা", "ammu": "আম্মু", "mata": "মাতা", "mother": "মা", "mum": "মা",
    "dada": "দাদা", "dadu": "দাদু", "grandpa": "দাদা",
    "dadi": "দাদী", "grandma": "দাদী",
    "nana": "নানা", "nanu": "নানা",
    "nani": "নানী",
    "chacha": "চাচা", "kaka": "কাকা", "uncle": "চাচা",
    "chachi": "চাচী", "kaki": "কাকী", "aunty": "আন্টি",
    "mama": "মামা", "mami": "মামী",
    "fufu": "ফুফু", "pishi": "পিসি",
    "fufa": "ফুফা", "pisha": "পিসা",
    "khalu": "খালু", "khala": "খালা", "mashi": "মাসি", "mesho": "মেশো",
    "chele": "ছেলে", "putro": "পুত্র", "son": "ছেলে", "boy": "ছেলে",
    "meye": "মেয়ে", "konna": "কন্যা", "daughter": "মেয়ে", "girl": "মেয়ে",
    "shish": "শিশু", "bacha": "বাচ্চা", "kid": "বাচ্চা", "baby": "বাবু",
    "shami": "স্বামী", "husband": "স্বামী", "bor": "বর",
    "bou": "বউ", "wife": "বউ", "stree": "স্ত্রী",
    "jamai": "জামাই",
    "shoshur": "শ্বশুর", "shashuri": "শাশুড়ি",
    "vabe": "ভাবি", "vabi": "ভাবি", "bhabi": "ভাবি",
    "jaja": "জা",
    "nond": "ননদ",
    "debor": "দেবর",
    "shal": "শালা", "shali": "শালি",
    "bondhu": "বন্ধু", "dost": "দোস্ত", "friend": "বন্ধু",
    "sat": "সাথী", "shathi": "সাথী", "partner": "সাথী",
    "protibeshi": "প্রতিবেশী", "neighbor": "প্রতিবেশী",
    "shikkhok": "শিক্ষক", "teacher": "শিক্ষক", "sir": "স্যার",
    "chatro": "ছাত্র", "student": "ছাত্র",
    "daktar": "ডাক্তার", "doctor": "ডাক্তার",
    "rogi": "রোগী", "patient": "রোগী",
    "police": "পুলিশ", "daroga": "দারোগা",

    # Body Parts
    "matha": "মাথা", "head": "মাথা",
    "chul": "চুল", "hair": "চুল",
    "chokh": "চোখ", "eye": "চোখ",
    "kan": "কান", "ear": "কান",
    "nak": "নাক", "nose": "নাক",
    "mukh": "মুখ", "mouth": "মুখ", "face": "মুখ",
    "dat": "দাঁত", "tooth": "দাঁত",
    "jib": "জিহ্বা", "tongue": "জিহ্বা",
    "gola": "গলা", "neck": "গলা", "throat": "গলা",
    "hat": "হাত", "hand": "হাত", "arm": "হাত",
    "angul": "আঙুল", "finger": "আঙুল",
    "nokh": "নখ", "nail": "নখ",
    "pa": "পা", "leg": "পা", "foot": "পা",
    "pet": "পেট", "stomach": "পেট",
    "buk": "বুক", "chest": "বুক",
    "pith": "পিঠ", "back": "পিঠ",
    "sorir": "শরীর", "body": "শরীর", "deho": "দেহ",
    "rokto": "রক্ত", "blood": "রক্ত",
    "hri": "হৃদয়", "heart": "হৃদয়", "dil": "দিল",

    # Houses & Places
    "bari": "বাড়ি", "home": "বাড়ি", "house": "বাড়ি",
    "ghor": "ঘর", "room": "ঘর",
    "basha": "বাসা",
    "office": "অফিস",
    "school": "স্কুল", "college": "কলেজ", "varsity": "ভার্সিটি", "university": "বিশ্ববিদ্যালয়",
    "hospital": "হাসপাতাল",
    "bank": "ব্যাংক",
    "bazar": "বাজার", "market": "মার্কেট", "hut": "হাট",
    "rasta": "রাস্তা", "road": "রোড", "path": "পথ", "way": "পথ",
    "goli": "গলি", "land": "জমি", "jom": "জমি",
    "sho": "শহর", "city": "শহর", "town": "শহর",
    "gram": "গ্রাম", "village": "গ্রাম",
    "thana": "থানা", "police station": "থানা",
    "zila": "জেলা", "district": "জেলা",
    "desh": "দেশ", "country": "দেশ",
    "bidesh": "বিদেশ", "foreign": "বিদেশ",
    "masjid": "মসজিদ", "mosque": "মসজিদ",
    "mandir": "মন্দির", "temple": "মন্দির",
    "park": "পার্ক", "math": "মাঠ", "field": "মাঠ",
    "nodi": "নদী", "river": "নদী",
    "pukur": "পুকুর", "pond": "পুকুর",
    "sagor": "সাগর", "sea": "সাগর", "ocean": "মহাসাগর",
    "pahar": "পাহাড়", "hill": "পাহাড়", "mountain": "পাহাড়",
    "jungle": "জঙ্গল", "bon": "বন", "forest": "বন",

    # Time & Calendar
    "shomoy": "সময়",
    "muhurto": "মুহূর্ত", "moment": "মুহূর্ত",
    "ghonta": "ঘণ্টা", "hour": "ঘণ্টা", "hr": "ঘণ্টা",
    "min": "মিনিট", "m": "মিনিট",
    "sec": "সেকেন্ড", "s": "সেকেন্ড",
    "din": "দিন", "day": "দিন",
    "rat": "রাত", "night": "রাত",
    "sokal": "সকাল", "morning": "সকাল",
    "dupur": "দুপুর", "noon": "দুপুর",
    "bikal": "বিকেল", "afternoon": "বিকেল",
    "shondha": "সন্ধ্যা", "evening": "সন্ধ্যা",
    "shoptaho": "সপ্তাহ", "week": "সপ্তাহ",
    "mash": "মাস", "month": "মাস",
    "bochor": "বছর", "year": "বছর", "yr": "বছর",
    "jug": "যুগ",
    "shotabdi": "শতাব্দী", "century": "শতাব্দী",
    "aj": "আজ", "ajke": "আজকে",
    "kal": "কাল", "kalke": "কালকে",
    "agamikal": "আগামীকাল", "tmrw": "আগামীকাল",
    "gotokal": "গতকাল", "yesterday": "গতকাল",
    "porshu": "পরশু",
    "ekhon": "এখন", "now": "এখন",
    "tokhon": "তখন", "then": "তখন",
    "kakhono": "কখনো", "ever": "কখনো",
    "kokhono na": "কখনো না", "never": "কখনো না",
    "shobshomoy": "সবসময়", "always": "সবসময়",
    "majhe majhe": "মাঝে মাঝে", "sometimes": "মাঝে মাঝে",
    "age": "আগে", "before": "আগে",
    "pore": "পরে", "after": "পরে", "later": "পরে",
    "shuru": "শুরু", "start": "শুরু",
    "shesh": "শেষ", "end": "শেষ", "finish": "শেষ",

    # Food & Kitchen (NityMulya relevant)
    "vat": "ভাত",
    "ruti": "রুটি", "bread": "রুটি",
    "porota": "পরোটা",
    "luchi": "লুচি",
    "biriyani": "বিরিয়ানি",
    "polao": "পলাও",
    "khichuri": "খিচুড়ি",
    "tor": "তরকারি", "torkari": "তরকারি", "curry": "তরকারি",
    "dal": "ডাল",
    "vaji": "ভাজি", "fry": "ভাজি",
    "vorta": "ভর্তা",
    "mach": "মাছ",
    "mangsho": "মাংস",
    "murgi": "মুরগি",
    "goru": "গরু", "beef": "গরুর মাংস",
    "khashi": "খাসি", "mutton": "খাসির মাংস",
    "dim": "ডিম",
    "dudh": "দুধ", "milk": "দুধ",
    "doi": "দই", "curd": "দই", "yogurt": "দই",
    "maakhon": "মাখন", "butter": "মাখন",
    "paneer": "পনির", "cheese": "পনির",
    "cha": "চা", "tea": "চা",
    "coffee": "কফি",
    "sharbat": "শরবত", "juice": "জুস",
    "pani": "পানি",
    "misti": "মিষ্টি", "sweet": "মিষ্টি",
    "chini": "চিনি",
    "lobon": "লবন",
    "tel": "তেল",
    "mosola": "মসলা", "spice": "মসলা",
    "holud": "হলুদ", "turmeric": "হলুদ",
    "morich": "মরিচ", "chili": "মরিচ",
    "ji": "জিরা", "cumin": "জিরা",
    "dhone": "ধনে", "coriander": "ধনে",
    "elach": "এলাচ",
    "daruchini": "দারুচিনি",
    "long": "লবঙ্গ",
    "ada": "আদা",
    "roshun": "রসুন",
    "peyaj": "পেঁয়াজ",
    "alu": "আলু",
    "begun": "বেগুন", "brinjal": "বেগুন", "eggplant": "বেগুন",
    "potol": "পটল",
    "korola": "করলা",
    "lau": "লাউ",
    "kumra": "কুমড়া", "pumpkin": "কুমড়া",
    "gajor": "গাজর", "carrot": "গাজর",
    "mula": "মুলা",
    "shosha": "শসা", "cucumber": "শসা",
    "lebu": "লেবু", "lemon": "লেবু",
    "tomato": "টমেটো",
    "dhrosh": "ঢেঁড়স", "ladies finger": "ঢেঁড়স",
    "fulkopi": "ফুলকপি", "cauliflower": "ফুলকপি",
    "badhakopi": "বাঁধাকপি", "cabbage": "বাঁধাকপি",
    "palong": "পালং", "spinach": "পালং শাক",
    "shak": "শাক",
    "kola": "কলা", "banana": "কলা",
    "am": "আম", "mango": "আম",
    "kathal": "কাঁঠাল", "jackfruit": "কাঁঠাল",
    "jam": "জাম",
    "lichu": "লিচু", "lychee": "লিচু",
    "peyara": "পেয়ারা", "guava": "পেয়ারা",
    "anarosh": "আনারস", "pineapple": "আনারস",
    "komola": "কমলা", "orange": "কমলা",
    "apple": "আপেল",
    "angur": "আঙ্গুর", "grape": "আঙ্গুর",
    "nashpati": "নাশপাতি", "pear": "নাশপাতি",
    "boroi": "বড়ই", "kul": "কুল",
    "narikel": "নারকেল", "coconut": "নারকেল",
    "khejur": "খেজুর", "date": "খেজুর",

    # Objects & Items
    "boi": "বই", "book": "বই",
    "kolom": "কলম", "pen": "কলম",
    "khata": "খাতা", "notebook": "খাতা",
    "kagoch": "কাগজ", "paper": "কাগজ",
    "bag": "ব্যাগ",
    "ghori": "ঘড়ি", "watch": "ঘড়ি", "clock": "ঘড়ি",
    "choshma": "চশমা", "glasses": "চশমা",
    "juta": "জুতা", "shoe": "জুতা",
    "muja": "মোজা", "sock": "মোজা",
    "jama": "জামা", "dress": "জামা",
    "kapor": "কাপড়", "cloth": "কাপড়",
    "shari": "শাড়ি",
    "punjabi": "পাঞ্জাবি",
    "shirt": "শার্ট",
    "pant": "প্যান্ট",
    "lungi": "লুঙ্গি",
    "tupi": "টুপি", "cap": "টুপি",
    "chair": "চেয়ার",
    "table": "টেবিল",
    "bichana": "বিছানা", "bed": "বিছানা",
    "fan": "ফ্যান",
    "light": "লাইট",
    "mobile": "মোবাইল",
    "laptop": "ল্যাপটপ",
    "computer": "কম্পিউটার",
    "tv": "টিভি",
    "fridge": "ফ্রিজ",
    "oven": "ওভেন",
    "gari": "গাড়ি", "car": "গাড়ি",
    "chabi": "চাবি", "key": "চাবি",
    "taka": "টাকা",
    "wallet": "মানিব্যাগ",
    "card": "কার্ড",
    "bottle": "বোতল",

    # Nature
    "akash": "আকাশ", "sky": "আকাশ",
    "surjo": "সূর্য", "sun": "সূর্য",
    "chad": "চাঁদ", "moon": "চাঁদ",
    "tara": "তারা", "star": "তারা",
    "megh": "মেঘ", "cloud": "মেঘ",
    "bristi": "বৃষ্টি", "rain": "বৃষ্টি",
    "jor": "ঝড়", "storm": "ঝড়",
    "batash": "বাতাস", "air": "বাতাস", "wind": "বাতাস",
    "alo": "আলো", "light": "আলো",
    "ondhokar": "অন্ধকার", "dark": "অন্ধকার",
    "ag": "আগুন", "fire": "আগুন",
    "pani": "পানি", "water": "পানি",
    "mati": "মাটি", "soil": "মাটি", "earth": "মাটি",
    "gach": "গাছ", "tree": "গাছ",
    "pata": "পাতা", "leaf": "পাতা",
    "ful": "ফুল", "flower": "ফুল",
    "fol": "ফল", "fruit": "ফল",
    "ghas": "ঘাস", "grass": "ঘাস",

    # Animals
    "prani": "প্রাণী", "animal": "প্রাণী",
    "pakhi": "পাখি", "bird": "পাখি",
    "poka": "পোকামাকড়", "insect": "পোকা",
    "kukur": "কুকুর", "dog": "কুকুর",
    "biral": "বিড়াল", "cat": "বিড়াল",
    "goru": "গরু", "cow": "গরু",
    "chhagol": "ছাগল", "goat": "ছাগল",
    "vera": "ভেড়া", "sheep": "ভেড়া",
    "has": "হাঁস", "duck": "হাঁস",
    "murgi": "মুরগি", "hen": "মুরগি", "cock": "মোরগ",
    "ghora": "ঘোড়া", "horse": "ঘোড়া",
    "hat": "হাতি", "elephant": "হাতি",
    "bagh": "বাঘ", "tiger": "বাঘ",
    "shingho": "সিংহ", "lion": "সিংহ",
    "banor": "বানর", "monkey": "বানর",
    "shap": "সাপ", "snake": "সাপ",
    "mach": "মাছ", "fish": "মাছ",
    "masha": "মশা", "mosquito": "মশা",
    "mach": "মাছি", "fly": "মাছি",

    # Adjectives & Feelings
    "valo": "ভালো", "good": "ভালো", "fine": "ভালো",
    "kharap": "খারাপ", "bad": "খারাপ",
    "sundor": "সুন্দর", "beautiful": "সুন্দর", "pretty": "সুন্দর",
    "osundor": "অসুন্দর", "ugly": "কুৎসিত",
    "khushi": "খুশি", "happy": "খুশি",
    "dukkho": "দুঃখ", "sad": "দুঃখিত", "upset": "মন খারাপ",
    "rag": "রাগ", "angry": "রাগী",
    "voy": "ভয়", "fear": "ভয়", "scared": "ভীত",
    "shahosh": "সাহস", "brave": "সাহসী",
    "laja": "লজ্জা", "shy": "লজ্জা",
    "shanti": "শান্তি", "peace": "শান্তি",
    "oshanti": "অশান্তি",
    "norom": "নরম", "soft": "নরম",
    "shokto": "শক্ত", "hard": "শক্ত",
    "gorom": "গরম", "hot": "গরম",
    "thanda": "ঠান্ডা", "cold": "ঠান্ডা",
    "bhari": "ভারী", "heavy": "ভারী",
    "halka": "হালকা", "light": "হালকা",
    "notun": "নতুন", "new": "নতুন",
    "puran": "পুরনো", "old": "পুরনো",
    "bacha": "কাঁচা", "raw": "কাঁচা",
    "paka": "পাকা", "ripe": "পাকা",
    "shukna": "শুকনা", "dry": "শুকনা",
    "vija": "ভেজা", "wet": "ভেজা",
    "porishkar": "পরিষ্কার", "clean": "পরিষ্কার",
    "nongra": "নোংরা", "dirty": "নোংরা",
    "jotil": "জটিল", "complex": "জটিল",
    "shohoj": "সহজ", "easy": "সহজ",
    "kothin": "কঠিন", "hard": "কঠিন",
    "shosta": "শস্তা", "cheap": "শস্তা",
    "dami": "দামী", "expensive": "দামী",
    "dhoni": "ধনী", "rich": "ধনী",
    "gorib": "গরীব", "poor": "গরীব",
    "mot": "মোটা", "fat": "মোটা",
    "chikon": "চিকন", "thin": "চিকন",
    "lomba": "লম্বা", "tall": "লম্বা", "long": "লম্বা",
    "khato": "খাটো", "short": "খাটো",
    "boro": "বড়", "big": "বড়", "large": "বড়",
    "choto": "ছোট", "small": "ছোট",
    "druto": "দ্রুত", "fast": "দ্রুত",
    "aste": "আস্তে", "slow": "আস্তে",
    "beshi": "বেশি", "much": "বেশি", "many": "অনেক",
    "kom": "কম", "less": "কম",
    "shothik": "সঠিক", "right": "সঠিক",
    "vul": "ভুল", "wrong": "ভুল",
    "sot": "সৎ", "honest": "সৎ",
    "oshot": "অসৎ", "dishonest": "অসৎ",
    "chalak": "চালাক", "clever": "চালাক",
    "boka": "বোকা", "stupid": "বোকা",
    "pagol": "পাগল", "mad": "পাগল", "crazy": "পাগল",
    "shustho": "সুস্থ", "healthy": "সুস্থ",
    "oshustho": "অসুস্থ", "sick": "অসুস্থ", "ill": "অসুস্থ",
    "klante": "ক্লান্ত", "tired": "ক্লান্ত",
    "ghum": "ঘুম", "sleep": "ঘুম",
    "khid": "ক্ষুধা", "hungry": "ক্ষুধার্ত",
    "pipasha": "পিপাসা", "thirsty": "পিপাসার্ত",

    # Verbs (Action words - Mix of tenses and roots)
    "kor": "কর", "do": "কর", "kora": "করা",
    "kori": "করি", "koro": "করো", "koren": "করেন",
    "korbo": "করব", "korbe": "করবে", "korben": "করবেন",
    "korechi": "করেছি", "korecho": "করেছ", "korechen": "করেছেন",
    "korchilam": "করছিলাম", "korchilo": "করছিল",
    
    "ja": "যা", "go": "যা", "jawa": "যাওয়া",
    "jai": "যাই", "jao": "যাও", "jan": "যান",
    "jacchi": "যাচ্ছি", "jaccho": "যাচ্ছ", "jacchen": "যাচ্ছেন",
    "jabo": "যাব", "jabe": "যাবে", "jaben": "যাবেন",
    "giyechi": "গিয়েছি", "giyecho": "গিয়েছ", "giyechen": "গিয়েছেন",
    
    "ash": "আয়", "come": "আসা", "asha": "আসা",
    "ashi": "আসি", "asho": "আসো", "ashen": "আসেন",
    "asch": "আসছি", "ascho": "আসছ", "aschen": "আসছেন",
    "ashbo": "আসব", "ashbe": "আসবে", "ashben": "আসবেন",
    "esechi": "এসেছি", "esecho": "এসেছ", "esechen": "এসেছেন",

    "kha": "খা", "eat": "খাওয়া", "khawa": "খাওয়া",
    "khai": "খাই", "khao": "খাও", "khan": "খান",
    "khacchi": "খাচ্ছি", "khaccho": "খাচ্ছ", "khacchen": "খাচ্ছেন",
    "khabo": "খাব", "khabe": "খাবে", "khaben": "খাবেন",
    "kheyechi": "খেয়েছি", "kheyecho": "খেয়েছ", "kheyechen": "খেয়েছেন",

    "de": "দে", "give": "দেওয়া", "dewa": "দেওয়া",
    "dei": "দেই", "dao": "দাও", "den": "দেন",
    "dicchi": "দিচ্ছি", "diccho": "দিচ্ছ", "dicchen": "দিচ্ছেন",
    "dibo": "দিব", "dibe": "দিবে", "diben": "দিবেন",
    "diyechi": "দিয়েছি", "diyecho": "দিয়েছ", "diyechen": "দিয়েছেন",

    "ne": "নে", "take": "নেওয়া", "newa": "নেওয়া",
    "nei": "নেই", "nao": "নাও", "nen": "নেন",
    "nicchi": "নিচ্ছি", "niccho": "নিচ্ছ", "nicchen": "নিচ্ছেন",
    "nibo": "নিব", "nibe": "নিবে", "niben": "নিবেন",
    "niyechi": "নিয়েছি", "niyecho": "নিয়েছ", "niyechen": "নিয়েছেন",

    "dekh": "দেখ", "see": "দেখা", "dekha": "দেখা", "look": "তাকানো", "watch": "দেখা",
    "dekhi": "দেখি", "dekho": "দেখো", "dekhen": "দেখেন",
    "dekhchi": "দেখছি", "dekhcho": "দেখছ", "dekhchen": "দেখছেন",
    "dekhbo": "দেখব", "dekhbe": "দেখবে", "dekhben": "দেখবেন",
    "dekhechi": "দেখেছি", "dekhecho": "দেখেছ", "dekhechen": "দেখেছেন",

    "shon": "শোন", "listen": "শোনা", "shona": "শোনা", "hear": "শোনা",
    "shuni": "শুনি", "shuno": "শোনো", "shunen": "শোনেন",
    "shunchi": "শুনছি", "shuncho": "শুনছ", "shunchen": "শুনছেন",
    "shunbo": "শুনব", "shunbe": "শুনবে", "shunben": "শুনবেন",
    "shunechi": "শুনেছি", "shunecho": "শুনেছ", "shunechen": "শুনেছেন",

    "bol": "বল", "say": "বলা", "bola": "বলা", "tell": "বলা",
    "boli": "বলি", "bolo": "বলো", "bolen": "বলেন",
    "bolchi": "বলছি", "bolcho": "বলছ", "bolchen": "বলছেন",
    "bolbo": "বলব", "bolbe": "বলবে", "bolben": "বলবেন",
    "bolechi": "বলেছি", "bolecho": "বলেছ", "bolechen": "বলেছেন",

    "thak": "থাক", "stay": "থাকা", "thaka": "থাকা", "live": "বাস করা",
    "thaki": "থাকি", "thako": "থাকো", "thaken": "থাকেন",
    "thakbo": "থাকব", "thakbe": "থাকবে", "thakben": "থাকবেন",

    "por": "পড়", "read": "পড়া", "pora": "পড়া", "study": "পড়ালেখা করা",
    "pori": "পড়ি", "poro": "পড়ো", "poren": "পড়েন",
    "porchi": "পড়ছি", "porcho": "পড়ছ", "porchen": "পড়ছেন",
    "porbo": "পড়ব", "porbe": "পড়বে", "porben": "পড়বেন",

    "likh": "লিখ", "write": "লেখা", "lekha": "লেখা",
    "likhi": "লিখি", "likho": "লিখো", "likhen": "লিখেন",
    "likhchi": "লিখছি", "likhcho": "লিখছ", "likhchen": "লিখছেন",
    "likhbo": "লিখব", "likhbe": "লিখবে", "likhben": "লিখবেন",

    "ghum": "ঘুমা", "sleep": "ঘুমানো", "ghumano": "ঘুমানো",
    "ghumai": "ঘুমাই", "ghumao": "ঘুমাও", "ghuman": "ঘুমান",
    "ghumacchi": "ঘুমাচ্ছি",
    "ghumabo": "ঘুমাব",

    "uth": "উঠ", "utha": "ওঠা", "get up": "ওঠা",
    "uthi": "উঠি", "utho": "উঠো", "uthen": "উঠেন",
    "uthbo": "উঠব",

    "bosh": "বস", "bosha": "বসা", "sit": "বসা",
    "boshi": "বসি", "bosho": "বসো", "boshen": "বসেন",
    "boshbo": " বসব",

    "chola": "চলা", "walk": "হাঁটা", "move": "চলা",
    "choli": "চলি", "cholo": "চলো", "cholen": "চলেন",
    "cholbo": "চলব",

    "ken": "কিন", "buy": "কেনা", "kena": "কেনা",
    "kini": "কিন", "kino": "কিনো", "kinen": "কিনেন",
    "kinbo": "কিনব", "kinbe": "কিনবে", "kinben": "কিনবেন",
    "kinechi": "কিনেছি",

    "bech": "বেচ", "sell": "বেচা", "becha": "বেচা",
    "bechi": "বেচি", "becho": "বেচো", "bechen": "বেচেন",
    "bechbo": "বেচব",

    "path": "পাঠা", "send": "পাঠানো", "pathano": "পাঠানো",
    "patha": "পাঠাই", "pathao": "পাঠাও", "pathan": "পাঠান",
    "pathabo": "পাঠাব", "pathacchi": "পাঠাচ্ছি",

    "khuj": "খুঁজ", "find": "খোঁজা", "khoja": "খোঁজা", "search": "খোঁজা",
    "khuji": "খুঁজি", "khujo": "খুঁজো", "khujen": "খুঁজেন",
    "khujbo": "খুঁজব",

    "pawa": "পাওয়া", "get": "পাওয়া",
    "pai": "পাই", "pao": "পাও", "pan": "পান",
    "pabo": "পাব", "pabe": "পাবে", "paben": "পাবেন",
    "peyechi": "পেয়েছি",

    "har": "হারা", "lose": "হারানো", "harano": "হারানো",
    "hariye": "হারিয়ে", "harsi": "হারিয়েছি", "hariyesi": "হারিয়েছি",

    "thama": "থামা", "stop": "থামা",
    "thami": "থামি", "thamo": "থামো", "thamen": "থামেন",
    "thambo": "থামব",

    "kaj": "কাজ", "work": "কাজ",
    "kaj kora": "কাজ করা", "working": "কাজ করছি", 

    "ranna": "রান্না", "cook": "রান্না করা", "cooking": "রান্না করছি",
    "khel": "খেল", "play": "খেলা", "khela": "খেলা",
    "hash": "হাস", "smile": "হাসা", "laugh": "হাসা",
    "kad": "াঁদ", "cry": "কাঁদা",
    "valobash": "ভালোবাস", "love": "ভালোবাসা", "like": "পছন্দ করা",
    "ghrina": "ঘৃণা", "hate": "ঘৃণা করা",
    "chinta": "চিন্তা", "think": "চিন্তা করা", "worry": "চিন্তা করা",
    "mone kora": "মনে করা", "remember": "মনে রাখা",
    "vule jawa": "ভুলে যাওয়া", "forget": "ভুলে যাওয়া",
    "biswas": "বিশ্বাস", "believe": "বিশ্বাস করা", "trust": "বিশ্বাস করা",
    
    # Numbers (Expanded)
    "shunno": "শূন্য", "zero": "শূন্য",
    "ek": "এক", "one": "এক", "1": "এক",
    "dui": "দুই", "two": "দুই", "2": "দুই",
    "tin": "তিন", "three": "তিন", "3": "তিন",
    "char": "চার", "four": "চার", "4": "চার",
    "pach": "পাঁচ", "five": "পাঁচ", "5": "পাঁচ",
    "choy": "ছয়", "six": "ছয়", "6": "ছয়",
    "shat": "সাত", "seven": "সাত", "7": "সাত",
    "at": "আট", "eight": "আট", "8": "আট",
    "noy": "নয়", "nine": "নয়", "9": "নয়",
    "dosh": "দশ", "ten": "দশ", "10": "দশ",
    "egaro": "এগারো", "eleven": "এগারো",
    "baro": "বারো", "twelve": "বারো",
    "tero": "তেরো", "thirteen": "তেরো",
    "choddo": "চৌদ্দ", "fourteen": "চৌদ্দ",
    "ponero": "পনেরো", "fifteen": "পনেরো",
    "sholo": "ষোল", "sixteen": "ষোল",
    "shotero": "সতেরো", "seventeen": "সতেরো",
    "atharo": "আঠারো", "eighteen": "আঠারো",
    "unish": "ঊনিশ", "nineteen": "ঊনিশ",
    "bish": "বিশ", "twenty": "বিশ",
    "pachish": "পঁচিশ",
    "ponchash": "পঞ্চাশ", "fifty": "পঞ্চাশ",
    "eksho": "একশ", "hundred": "একশ",
    "hajar": "হাজার", "thousand": "হাজার",
    "lokkho": "লক্ষ", "lakh": "লক্ষ", "lac": "লক্ষ",
    "koti": "কোটি", "crore": "কোটি",
    "ordhek": "অর্ধেক", "half": "অর্ধেক",

    # Colors
    "shada": "সাদা", "white": "সাদা",
    "kalo": "কালো", "black": "কালো",
    "lal": "লাল", "red": "লাল",
    "nil": "নীল", "blue": "নীল",
    "sobuj": "সবুজ", "green": "সবুজ",
    "holud": "হলুদ", "yellow": "হলুদ",
    "komola": "কমলা", "orange": "কমলা",
    "golapi": "গোলাপী", "pink": "গোলাপী",
    "beguni": "বেগুনী", "purple": "বেগুনী",
    "badami": "বাদামী", "brown": "বাদামী",
    "sonali": "সোনালী", "golden": "সোনালী",
    "rupali": "রূপালী", "silver": "রূপালী",

    # Miscellaneous / Grammar / Prepositions
    "ebong": "এবং", "ar": "আর", "o": "ও",
    "kintu": "কিন্তু", "tobe": "তবে",
    "ba": "বা", "othoba": "অথবা", "or": "অথবা",
    "jodi": "যদি", "if": "যদি",
    "tai": "তাই", "so": "তাই",
    "kar": "কার", "whose": "কার",
    "ki": "কি", "what": "কি",
    "kobe": "কবে", "when": "কবে", "kokhon": "কখন",
    "kothay": "কোথায়", "where": "কোথায়",
    "kivabe": "কিভাবে", "how": "কিভাবে", "kemon": "কেমন",
    "keno": "কেন", "why": "কেন",
    "kara": "কারা", "who": "কে", "ke": "কে",
    "kon": "কোন", "which": "কোন",
    "shathe": "সাথে", "with": "সাথে",
    "chara": "ছাড়া", "without": "ছাড়া",
    "jonno": "জন্য", "for": "জন্য",
    "theke": "থেকে", "from": "থেকে",
    "kache": "কাছে", "near": "কাছে",
    "dure": "দূরে", "far": "দূরে",
    "upore": "উপরে", "on": "উপরে", "up": "উপরে",
    "niche": "নিচে", "under": "নিচে", "down": "নিচে",
    "vitore": "ভিতরে", "inside": "ভিতরে", "in": "ভিতরে",
    "baire": "বাইরে", "outside": "বাইরে", "out": "বাইরে",
    "samne": "সামনে", "front": "সামনে",
    "pichone": "পিছনে", "behind": "পিছনে", "back": "পিছনে",
    "pashe": "পাশে", "beside": "পাশে",
    "majhe": "মাঝে", "between": "মাঝে", "middle": "মাঝে",
    "dik": "দিক", "direction": "দিক",
    "bam": "বাম", "left": "বাম",
    "dan": "ডান", "right": "ডান",
    "soja": "সোজা", "straight": "সোজা",

    # Common Sentences Fragments / Greetings
    "assalamualaikum": "আসসালামু আলাইকুম",
    "walaikumassalam": "ওয়ালাইকুম আসসালাম",
    "namaskar": "নমস্কার",
    "adab": "আদাব",
    "gud": "গুড", 
    "mrng": "মর্নিং",
    "nyt": "নাইট",
    "hlo": "হ্যালো", "hello": "হ্যালো", "hi": "হাই",
    "bye": "বিদায়",
    "swagotom": "স্বাগতম", "welcome": "স্বাগতম",
    "maf": "মাফ", "sorry": "দুঃখিত", "khoma": "ক্ষমা",
    "thik ache": "ঠিক আছে", "okay": "ঠিক আছে", "ok": "ঠিক আছে",
    "ji": "জি", "ha": "হ্যাঁ", "yes": "হ্যাঁ",
    "na": "না", "no": "না",
}

def update_dictionary():
    if not os.path.exists(file_path):
        print("Dictionary file not found!")
        return

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            current_data = json.load(f)
    except json.JSONDecodeError:
        print("Error decoding existing JSON. Starting fresh or aborting.")
        return

    # Update with new data (this preserves old keys and overwrites if same key exists)
    # Since the request is "add more", we merge.
    # To handle potential casing issues, we can check lower case, but the previous pattern relies on exact keys mostly.
    # The new_data uses simple keys.
    
    current_data.update(new_data)
    
    # Sort for better readability (optional but nice)
    sorted_data = dict(sorted(current_data.items()))

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(sorted_data, f, ensure_ascii=False, indent=4)
        
    print(f"Successfully added {len(new_data)} entries. Total count: {len(sorted_data)}")

if __name__ == "__main__":
    update_dictionary()
